### ISSUE TITLE
media: support sending MediaStreams with multiple tracks

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#16]
Currently the media stream labels are hardcoded in the SDP offer and answer generation. The `RTCPeerConnection.AddTrack` should be extended to support adding media stream labels.

**TODO**
- [ ] Add a [variadic](https://gobyexample.com/variadic-functions) streams argument to the AddTrack method as specified in the [RTP Media API](https://w3c.github.io/webrtc-pc/#rtcpeerconnection-interface-extensions)
- [ ] Store the media stream ids on the RTCTrack object as specified [here](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtrack)
- [ ] Add the media streams to the SDP offer and answer. Some of the required logic already exists. However, the stream label is currently hardcoded to the track label. The procedure is specified in the [JSEP spec](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep)

**Comment by backkem** [comment]
For anyone interested in taking on this issue: Please check out #35. The purpose of the PR is to match the [WebRTC API](https://w3c.github.io/webrtc-pc/) more closely and it should serve as a good basis to implement MediaStream support. However, MediaStream support itself has been ignored for now.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 2 months, 4 weeks from now.
Please review their action plans below:


1. [vukovinski](https://gitcoin.co/profile/vukovinski) has started work. 
    
    Get familiar with the specs, expand the "func (r *RTCPeerConnection) AddTrack(track *RTCTrack) (*RTCRtpSender, error)" method and send a PR.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/pions/webrtc/16/868).

**Comment by backkem** [comment]
Welcome @vukovinski, glad to have you. We're very active on the #pions channel of the golang slack if you have any questions.

**Comment by notedit** [comment]
do we need implement unified-plan?

https://tools.ietf.org/html/draft-roach-mmusic-unified-plan-00

**Comment by backkem** [comment]
#54 has meanwhile been created to track unified-plan support.

**Comment by gitcoinbot** [comment]
@vukovinski Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by vukovinski** [comment]
Be happy bot :)

**Comment by gitcoinbot** [comment]
@vukovinski Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 1 month, 3 weeks from now.
Please review their action plans below:


1. [BR7braj](https://gitcoin.co/profile/BR7braj) has started work. 
    
    First I'll be going through the problem statement abd then come up with a plan

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/pions/webrtc/16/868).

**Comment by backkem** [comment]
Welcome @BR7braj. Looking forward to working with you. We're very active on the #pions channel of the golang slack if you have any questions.

**Comment by gitcoinbot** [comment]
@BR7braj Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by gitcoinbot** [comment]
@BR7braj Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by gitcoinbot** [comment]
@BR7braj Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by gitcoinbot** [comment]
@BR7braj Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by gitcoinbot** [comment]
@BR7braj Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by gitcoinbot** [comment]
@BR7braj Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by gitcoinbot** [comment]
@BR7braj Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by gitcoinbot** [comment]
@BR7braj Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by gitcoinbot** [comment]
@BR7braj Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by Sean-Der** [comment]
This was implemented.

`(pc *RTCPeerConnection) NewRTCTrack` allows you to pass MediaStream + track.

**Comment by gitcoinbot** [comment]
@BR7braj Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/16/868?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__The funding of 0.2 ETH  (45.26 USD @ $226.28/ETH) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $22,906.19 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
