### ISSUE TITLE
examples: exchange entire RTCSessionDescription

### ISSUE THREAD

**Issue by backkem** [pions/webrtc#39]
Currently we only exchange the SDP between the browser (JSFiddle) and the example, hard-coding the session description type on both sides. This should be changed so the entire RTCSessionDescription is exchanged. In addition, all examples should be adapted so the offer/answer direction can be changed.

Update: The [pion-to-pion](https://github.com/pions/webrtc/tree/master/examples/pion-to-pion) example exchanges the entire RTCSessionDescription in json format. This can be used as an example.

**TODO**
- [ ] Adapt gstreamer-receive
- [ ] Adapt gstreamer-send
- [ ] Adapt save-to-disk
- [ ] Adapt data-channels

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 2 months, 2 weeks from now.
Please review their action plans below:


1. [evgeniuz](https://gitcoin.co/profile/evgeniuz) has started work. 
    
    I want to try implementing this issue. Will check examples and adapt them.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/pions/webrtc/39/867).

**Comment by backkem** [comment]
Hi @evgeniuz. Awesome, glad to have you! Don't hesitate to ask any questions you may have. Please conciser joining the #pion channel of the gopher slack. It makes discussions a little easier plus we've got a great community in there.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__The funding of this issue was increased to 0.2 ETH (55.72 USD @ $278.58/ETH) .__

 
* If you want to claim the bounty you can do so [here](https://gitcoin.co/issue/pions/webrtc/39/867)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/pions/webrtc/39/867).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $19,550.30 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 1 month, 2 weeks from now.
Please review their action plans below:


1. [Peter-Takhar](https://gitcoin.co/profile/Peter-Takhar) has started work. 
    
    Familarize myself with project
First, work modifying the examples to exchange the  RTCSessionDescription and test changes.
Next, modify the example with offer/answer functionality.

Will able to dive into this fully once my classes are over this week.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/pions/webrtc/39/867).

**Comment by gitcoinbot** [comment]
@Peter-Takhar Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/pions/webrtc/39/867?snooze=1) | [3 days](https://gitcoin.co/issue/pions/webrtc/39/867?snooze=3) | [5 days](https://gitcoin.co/issue/pions/webrtc/39/867?snooze=5) | [10 days](https://gitcoin.co/issue/pions/webrtc/39/867?snooze=10) | [100 days](https://gitcoin.co/issue/pions/webrtc/39/867?snooze=100)

**Comment by millnitzluan** [comment]
This issue still opened?

**Comment by backkem** [comment]
Hi @millnitzluan. Yes, it is still open. JSON (un)marshaling of the RTCSessionDescriptions was added in #137 but the examples have not yet been adapted to exchange the entire RTCSessionDescription.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__The funding of 0.2 ETH  (34.11 USD @ $170.56/ETH) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $97,273.33 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
